export const SHIPPING_ADDRESS_DETAIL_REQUEST = "SHIPPING_ADDRESS_DETAIL_REQUEST";
export const SHIPPING_ADDRESS_DETAIL_SUCCESS = "SHIPPING_ADDRESS_DETAIL_SUCCESS";
export const SHIPPING_ADDRESS_DETAIL_FAIL = "SHIPPING_ADDRESS_DETAIL_FAIL";
export const SHIPPING_ADDRESS_DETAIL_RESET = "SHIPPING_ADDRESS_DETAIL_RESET";

export const SHIPPING_ADDRESS_CREATE_REQUEST = "SHIPPING_ADDRESS_CREATE_REQUEST";
export const SHIPPING_ADDRESS_CREATE_SUCCESS = "SHIPPING_ADDRESS_CREATE_SUCCESS";
export const SHIPPING_ADDRESS_CREATE_FAIL = "SHIPPING_ADDRESS_CREATE_FAIL";
export const SHIPPING_ADDRESS_CREATE_RESET = "SHIPPING_ADDRESS_CREATE_RESET";
